MvcCoreClienteWCF/Models/Cliente.cs
namespace MvcCoreClienteWCF.Models
{
    public class Cliente
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion {  get; set; }
        public string Email { get; set; }
        public string ImagenCliente { get; set; }
    }
}

MvcCoreClienteWCF/Models/ErrorViewModel.cs
namespace MvcCoreClienteWCF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreClienteWCF/Models/Provincia.cs
namespace MvcCoreClienteWCF.Models
{
    public class Provincia
    {
        public int IdProvincia { get; set; }
        public string Nombre { get; set; }
    }
}

MvcCoreClienteWCF/Controllers/CatastroController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClienteWCF.Models;
using MvcCoreClienteWCF.Services;

namespace MvcCoreClienteWCF.Controllers
{
    public class CatastroController : Controller
    {
        private ServiceCatastro service;

        public CatastroController(ServiceCatastro service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Provincia> provincias = await this.service.GetProvinciasAsync();
            return View(provincias);
        }

        public async Task<IActionResult> Municipios(string provincia)
        {
            List<string> municipios = await this.service.GetMunicipiosAsync(provincia);
            return View(municipios);
        }
    }
}

MvcCoreClienteWCF/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClienteWCF.Models;
using MvcCoreClienteWCF.Repositories;

namespace MvcCoreClienteWCF.Controllers
{
    public class ClientesController : Controller
    {
        private RepositoryClientesXML repo;

        public ClientesController(RepositoryClientesXML repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Cliente> clientes = this.repo.GetClientes();
            return View(clientes);
        }

        public IActionResult Details(int idcliente)
        {
            Cliente cliente = this.repo.FindCliente(idcliente);
            return View(cliente);
        }

    }
}

MvcCoreClienteWCF/Controllers/ConversorController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClienteWCF.Services;

namespace MvcCoreClienteWCF.Controllers
{
    public class ConversorController : Controller
    {
        private ServiceConversor service;

        public ConversorController(ServiceConversor service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string numeros)
        {
            string data = await this.service.ConvertNumberToWordsAsync(numeros);
            ViewData["DATOS"] = data;
            return View();
        }
    }
}

MvcCoreClienteWCF/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClienteWCF.Services;
using ServiceCountriesNameSpace;

namespace MvcCoreClienteWCF.Controllers
{
    public class CountriesController : Controller
    {
        private ServiceCountries service;

        public CountriesController(ServiceCountries service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            tCountryCodeAndName[] countries = await this.service.GetCountriesAsync();
            return View(countries);
        }

        public async Task<IActionResult> Details(string isoCode)
        {
            tCountryInfo country = await this.service.GetCountryInfoAsync(isoCode);
            return View(country);
        }
    }
}

MvcCoreClienteWCF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClienteWCF.Models;
using System.Diagnostics;

namespace MvcCoreClienteWCF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreClienteWCF/Controllers/MetodosVariosController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreClienteWCF.Controllers
{
    public class MetodosVariosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

MvcCoreClienteWCF/Views/Catastro/Index.cshtml
@model List<Provincia>

<h1>Service Catastro XML</h1>


<ul class="list-group">
    @foreach(Provincia prov in Model){
        <li class="list-group-item">
            @prov.Nombre
            <a asp-controller="Catastro" asp-action="Municipios" asp-route-provincia="@prov.Nombre">
                Municipios
            </a>
        </li>
    }
</ul>

MvcCoreClienteWCF/Views/Catastro/Municipios.cshtml
@model List<string>

<h1>Municipios</h1>

<p>
    <a asp-action="Index" asp-controller="Catastro">
        Back to Index
    </a>
</p>

<ul class="list-group">
    @foreach(string muni in Model)
    {
        <li class="list-group-item list-group-item-warning">
            @muni
        </li>
    }
</ul>

MvcCoreClienteWCF/Views/Clientes/Details.cshtml
@model MvcCoreClienteWCF.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagenCliente)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Html.DisplayFor(model => model.ImagenCliente)" style="width:100px; height:100px" />
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcCoreClienteWCF/Views/Clientes/Index.cshtml
@model IEnumerable<MvcCoreClienteWCF.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagenCliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.ImagenCliente)" style="width:100px; height:100px" />
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { idcliente = item.IdCliente })
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreClienteWCF/Views/Conversor/Index.cshtml
<h1>Service Conversor WCF</h1>

<form method="post">
    <label>Introduzca numeros</label>
    <input type="text" name="numeros" class="form-control" />
    <button class="btn btn-success">
        Mostrar Words
    </button>
</form>

<h2>@ViewData["DATOS"]</h2>

MvcCoreClienteWCF/Views/Countries/Details.cshtml
@model ServiceCountriesNameSpace.tCountryInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>tCountryInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sISOCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sISOCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sCapitalCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sCapitalCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sPhoneCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sPhoneCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sContinentCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sContinentCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sCurrencyISOCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sCurrencyISOCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sCountryFlag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sCountryFlag)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcCoreClienteWCF/Views/Countries/Index.cshtml
@model tCountryCodeAndName[]

<ul class="list-group">
    @foreach(var country in Model)
    {
        <li class="list-group-item">
            @country.sName
            <a asp-controller="Countries" asp-action="Details" asp-route-isoCode="@country.sISOCode" class="btn btn-info">
                Details
            </a>
        </li>
    }
</ul>

MvcCoreClienteWCF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreClienteWCF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreClienteWCF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreClienteWCF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreClienteWCF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conversor" asp-action="Index">Conversor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catastro" asp-action="Index">Service Catastro XML</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreClienteWCF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>